content:
  - name: komarigoto
    label: 困りごと
    type: collection
    path: komarigoto/articles
    subfolders: true
    operations:
      rename: false
      delete: false
    fields:
      - name: 暮らし道具
        label: タイトル
        type: string
      - name: body
        label: 本文
        type: rich-text
